# Generated by Django 5.0.1 on 2024-01-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
        ('user_app', '0002_useradditional_delete_bloguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditional',
            name='liked_posts',
            field=models.ManyToManyField(related_name='liked_posts', to='post_app.post'),
        ),
    ]
